# Generated by Django 5.1.2 on 2025-01-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institue_name', models.CharField(db_index=True, default='', max_length=100)),
                ('awar_name', models.CharField(db_index=True, default='', max_length=100)),
                ('year', models.DateField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('_id', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('subject', models.CharField(db_index=True, default='', max_length=100)),
                ('contact_no', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('email', models.EmailField(db_index=True, default='', max_length=254)),
                ('message_detail', models.TextField(db_index=True, default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file_assignment', models.FileField(blank=True, db_index=True, null=True, upload_to='client/contact')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(db_index=True, default='', max_length=100)),
                ('degree', models.CharField(db_index=True, default='', max_length=100)),
                ('from_year', models.DateField(db_index=True)),
                ('to_year', models.DateField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('_id', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('media', models.ImageField(db_index=True, default='', upload_to='portfolio')),
                ('tag', models.CharField(db_index=True, default='', max_length=100)),
                ('image_pb_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenSaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.BooleanField(default=False)),
                ('chat_room_id', models.UUIDField(null=True)),
                ('users_messaging_container', models.ManyToManyField(blank=True, to='core_control.customuser')),
                ('fcm_token', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_control.tokensaver')),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousCookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_control.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='', editable=False, max_length=100, unique=True)),
                ('description', models.TextField(db_index=True, default='')),
                ('title', models.CharField(db_index=True, default='', max_length=100)),
                ('image', models.ManyToManyField(db_index=True, to='core_control.portfolioimages')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(db_index=True, upload_to='profiles')),
                ('slug', models.SlugField(default='', editable=False, max_length=100, unique=True)),
                ('image_pb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(db_index=True, default='', max_length=100)),
                ('bio', models.TextField(db_index=True)),
                ('experience', models.TextField(db_index=True)),
                ('awards', models.ManyToManyField(blank=True, db_index=True, to='core_control.awards')),
                ('education', models.ManyToManyField(db_index=True, to='core_control.education')),
                ('skills', models.ManyToManyField(db_index=True, to='core_control.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('_id', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image_pb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('services_slug', models.SlugField(blank=True, editable=False, max_length=300, unique=True)),
                ('description', models.TextField(db_index=True)),
                ('technologies', models.ManyToManyField(db_index=True, to='core_control.technologies')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
    ]
