# Generated by Django 5.1.2 on 2024-11-20 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services')),
                ('image_pb_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'blog_post_images',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('_id', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('subject', models.CharField(db_index=True, default='', max_length=100)),
                ('contact_no', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('email', models.EmailField(db_index=True, default='', max_length=254)),
                ('message_detail', models.TextField(db_index=True, default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file_assignment', models.FileField(blank=True, db_index=True, null=True, upload_to='client/contact')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('_id', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(related_name='blog_posts', to='core_control.blogpostimage')),
                ('comments', models.ManyToManyField(related_name='blog_posts', to='core_control.comment')),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('_id', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image_pb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='services')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('services_slug', models.SlugField(blank=True, editable=False, max_length=300, unique=True)),
                ('description', models.TextField(db_index=True)),
                ('technologies', models.ManyToManyField(db_index=True, to='core_control.technologies')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core_control.user'),
        ),
    ]
