# Generated by Django 5.1.2 on 2024-12-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('_id', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('subject', models.CharField(db_index=True, default='', max_length=100)),
                ('contact_no', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('email', models.EmailField(db_index=True, default='', max_length=254)),
                ('message_detail', models.TextField(db_index=True, default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file_assignment', models.FileField(blank=True, db_index=True, null=True, upload_to='client/contact')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('_id', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image_pb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='services')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('services_slug', models.SlugField(blank=True, editable=False, max_length=300, unique=True)),
                ('description', models.TextField(db_index=True)),
                ('technologies', models.ManyToManyField(db_index=True, to='core_control.technologies')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
    ]
