# Generated by Django 5.1.2 on 2025-01-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True),
        ),
    ]
