# Generated by Django 5.1.2 on 2024-11-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='services')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('services_slug', models.SlugField(blank=True, editable=False, max_length=300, unique=True)),
                ('description', models.TextField(db_index=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
