# Generated by Django 5.1.2 on 2024-12-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0001_initial'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
       
    ]
