# Generated by Django 5.1.2 on 2024-11-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, unique=True),
        ),
    ]
