# Generated by Django 5.1.2 on 2024-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0002_portfolioimages_alter_service_image_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(db_index=True, default='', upload_to='portfolio')),
                ('tag', models.CharField(db_index=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_index=True, default='')),
                ('image', models.ManyToManyField(db_index=True, to='core_control.portfolioimages')),
            ],
        ),
    ]
