# Generated by Django 5.1.2 on 2025-01-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0002_alter_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
