# Generated by Django 5.1.2 on 2024-12-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0003_portfolioimages_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institue_name', models.CharField(db_index=True, default='', max_length=100)),
                ('year', models.DateField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(db_index=True, default='', max_length=100)),
                ('degree', models.CharField(db_index=True, default='', max_length=100)),
                ('from_year', models.DateField(db_index=True)),
                ('to_year', models.DateField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(db_index=True, upload_to='profiles')),
                ('full_name', models.CharField(db_index=True, default='', max_length=100)),
                ('bio', models.TextField(db_index=True)),
                ('experience', models.TextField(db_index=True)),
                ('awards', models.ManyToManyField(db_index=True, to='core_control.awards')),
                ('education', models.ManyToManyField(db_index=True, to='core_control.education')),
                ('skills', models.ManyToManyField(db_index=True, to='core_control.skills')),
            ],
        ),
    ]
