# Generated by Django 5.1.2 on 2024-11-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0003_service_image_pb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('subject', models.CharField(db_index=True, default='', max_length=100)),
                ('email', models.EmailField(db_index=True, default='', max_length=254)),
                ('message_detail', models.TextField(db_index=True, default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='technologies',
            field=models.ManyToManyField(db_index=True, to='core_control.technologies'),
        ),
    ]
