# Generated by Django 5.1.2 on 2025-01-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0003_alter_portfolio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_pb_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True),
        ),
    ]
