# Generated by Django 5.1.2 on 2024-12-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0004_awards_education_skills_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='awar_name',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
