# Generated by Django 5.1.2 on 2025-01-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0004_profile_image_pb_id_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousCookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
