# Generated by Django 5.1.2 on 2024-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0004_contact_technologies_service_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file_assignment',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to='client/contact'),
        ),
    ]
