# Generated by Django 5.1.2 on 2024-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0005_awards_awar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
