# Generated by Django 5.1.2 on 2025-01-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0005_anonymouscookies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('anonymous_track_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_control.anonymouscookies')),
            ],
        ),
    ]
