# Generated by Django 5.1.2 on 2024-11-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0005_contact_file_assignment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUS',
        ),
    ]
