# Generated by Django 5.1.2 on 2025-01-19 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0007_customuser_admin_customuser_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='anonymous_track_key',
        ),
        migrations.AddField(
            model_name='anonymouscookies',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_control.customuser'),
        ),
    ]
