# Generated by Django 5.1.2 on 2025-01-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0008_remove_customuser_anonymous_track_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='users_messaging_container',
            field=models.ManyToManyField(blank=True, to='core_control.customuser'),
        ),
    ]
