# Generated by Django 5.1.2 on 2025-01-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0009_customuser_users_messaging_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_room_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
