# Generated by Django 5.1.2 on 2025-01-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0010_customuser_chat_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chat_room_id',
            field=models.UUIDField(null=True),
        ),
    ]
