# Generated by Django 5.1.2 on 2024-12-01 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostImageO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services')),
                ('image_pb_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'blog_post_images',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, default='', max_length=200)),
                ('post_slug', models.SlugField(blank=True, editable=False, max_length=300, unique=True)),
                ('content', models.TextField(default='')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(related_name='blog_postso', to='core_blog.blogpostimageo')),
                ('comments', models.ManyToManyField(related_name='blog_posts', to='core_blog.comment')),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core_blog.user'),
        ),
    ]
