# Generated by Django 5.1.2 on 2024-12-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_blog', '0002_blogpost_tag_alter_blogpost_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='core_blog.comment'),
        ),
    ]
