# Generated by Django 5.1.2 on 2025-01-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_last_message_time', models.DateTimeField(blank=True, null=True)),
                ('secondary_last_message_time', models.DateTimeField(blank=True, null=True)),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_primary_user', to='core_control.customuser')),
                ('secondary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_secondary_user', to='core_control.customuser')),
            ],
            options={
                'unique_together': {('primary_user', 'secondary_user')},
            },
        ),
        migrations.CreateModel(
            name='Chatmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_control.customuser')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage_thread', to='core_message.chatthread')),
            ],
            options={
                'ordering': ['message_time'],
            },
        ),
    ]
