# Generated by Django 5.1.2 on 2025-01-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
